
#####	CONFIG		############################################################
NAME		:= a.out
CFLAGS		= -Wall -Wextra -Werror -std=c++20

#####	SOURCES		############################################################
SRC			=	main.cpp


all:
	g++ ${CFLAGS} $(SRC) -o $(NAME)

.PHONY: all